# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 8, 11, 4, 0, 40, 814356, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
