# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170811_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
